### ISSUE TITLE
Exception running simple example

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [kerams/Templatus#17]
```
c:\TFS\PracticeManagement\dev\>"C:\TFS\PracticeManagement\dev\packages\Templatus.0.2.0\tools\Templatus.exe" -t "C:\TFS\PracticeManagement\dev\Project\Template.ttus" -p name=Timmy;age=3
Degree of parallelism: 1
Starting...


Unhandled Exception: System.Exception: Error creating evaluation session: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.FSharp.Compiler.MSBuildResolver.ResolveCore(ResolutionEnvironment resolutionEnvironment, Tuple`2[] references, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, String targetProcessorArchitecture, String outputDirectory, String fsharpCoreExplicitDirOrFSharpBinariesDir, FSharpList`1 explicitIncludeDirs, String implicitIncludeDir, String frameworkRegistryBase, String assemblyFoldersSuffix, String assemblyFoldersConditions, Boolean allowRawFileName, FSharpFunc`2 logmessage, FSharpFunc`2 logwarning, FSharpFunc`2 logerror)
   at Microsoft.FSharp.Compiler.MSBuildResolver.CallResolveCore@423(String targetProcessorArchitecture, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, ResolutionEnvironment resolutionEnvironment, String outputDirectory, FSharpFunc`2 logwarning, FSharpFunc`2 logmessage, FSharpFunc`2 logerror, String implicitIncludeDir, String fsharpCoreExplicitDirOrFSharpBinariesDir, String frameworkRegistryBase, FSharpList`1 explicitIncludeDirs, String assemblyFoldersSuffix, String assemblyFoldersConditions, Tuple`2[] references, Boolean allowRawFileName)
   at Microsoft.FSharp.Compiler.MSBuildResolver.Resolve(ResolutionEnvironment resolutionEnvironment, Tuple`2[] references, String targetFrameworkVersion, FSharpList`1 targetFrameworkDirectories, String targetProcessorArchitecture, String outputDirectory, String fsharpCoreExplicitDirOrFSharpBinariesDir, FSharpList`1 explicitIncludeDirs, String implicitIncludeDir, String frameworkRegistryBase, String assemblyFoldersSuffix, String assemblyFoldersConditions, FSharpFunc`2 logmessage, FSharpFunc`2 logwarning, FSharpFunc`2 logerror)
   at Microsoft.FSharp.Compiler.Build.Resolve@3016-1(TcConfig tcConfig, ResolveAssemblyReferenceMode mode, range errorAndWarningRange, String targetFrameworkMajorMinor, String targetProcessorArchitecture, String outputDirectory, FSharpList`1 targetFrameworkDirectories, Tuple`2[] references, Boolean showMessages)
   at Microsoft.FSharp.Compiler.Build.TcConfig.TryResolveLibsUsingMSBuildRules(TcConfig tcConfig, FSharpList`1 originalReferences, range errorAndWarningRange, ResolveAssemblyReferenceMode mode)
   at Microsoft.FSharp.Compiler.Build.TcAssemblyResolutions.Resolve(TcConfig tcConfig, FSharpList`1 assemblyList, FSharpList`1 knownUnresolved)
   at Microsoft.FSharp.Compiler.Build.TcAssemblyResolutions.SplitNonFoundationalResolutions(TcConfig tcConfig)
   at Microsoft.FSharp.Compiler.IncrementalFSharpBuild.GetFrameworkTcImports(TcConfig tcConfig)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at Microsoft.FSharp.Compiler.Interactive.Shell.-ctor@2498-115.Invoke(String message)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible)
   at Templatus.Core.OutputGenerator.generate(FSharpList`1 templateParameters, ProcessedTemplate processedTemplate)
   at Templatus.Main.fSuccess@1(FSharpFunc`2 f, ProcessedTemplate x, FSharpList`1 msgs)
   at Templatus.Main.processChunk@47-2.Invoke(Result`2 result)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Templatus.Main.processChunk@45.Invoke(FSharpList`1 list)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list)
   at Templatus.Main.main(String[] _arg1)
```

**Comment by kerams** [comment]
Do you have VS installed on that machine?

**Comment by ImaginaryDevelopment** [comment]
Yes VS 2010 SP1, and VS 2015 with SP1 are installed

**Comment by ImaginaryDevelopment** [comment]
with a runtime redirect of `"Microsoft.Build.Framework" (Version("14.0.0.0")) "b03f5f7f11d50a3a"` it works in Visual Studio with the code in my fork, but still fails to run in LINQPad with 

```
Degree of parallelism: 1

Starting...
Caught exception System.MissingMethodException: Method not found: 'FsiEvaluationSession FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig, System.String[], System.IO.TextReader, System.IO.TextWriter, System.IO.TextWriter, Microsoft.FSharp.Core.FSharpOption`1<Boolean>)'.
   at Templatus.Core.OutputGenerator.generate(FSharpList`1 templateParameters, ProcessedTemplate processedTemplate)
   at Templatus.Main.processChunk@64-9.Invoke(ProcessedTemplate processedTemplate)
   at Templatus.Main.processChunk@64-11.Invoke(Tuple`2 tupledArg)
   at Templatus.Main.processChunk@64-10.Invoke(Result`2 result)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list)
   at Templatus.Main.processChunk@62.Invoke(FSharpList`1 list)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list)
   at Templatus.Main.createOutput@73-6.Invoke(FSharpList`1 list)
   at Templatus.Main.main(String[] s)
   at <StartupCode$query_enjpgi>.$Main.main@() in C:\Users\User\AppData\Local\Temp\LINQPad5\_ogikuift\query_enjpgi.fs:line 12
```

**Comment by ImaginaryDevelopment** [comment]
Interestingly, as far as I've tried to figure out the error only occurring in LINQPad, it appears that at the point it loads the `OutputGenerator` module for some reason in LINQPad it attempts to load `FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` from `file:///C:/Program Files (x86)/Linqpad/Beta5/LINQPad.exe`

**Comment by kerams** [comment]
If I am not mistaken, the guys maintaining the compiler service have done some adjustments to the dependency on MSBuild recently. I think updating to the latest version is worth a shot as the first problem might just go away on its own.
As far as the second problem is concerned, I believe that the compiler services require` FSharp.Core.optdata` and `FSharp.Core.sigdata` right next to `FSharp.Core.dll`, which is why they're a part of Templatus' Nuget package. So, regardless of why LinqPad tries to load `FSharp.Core` from a different location, the absence of the 2 extra files might be the cause of the issue.
`FSharp.Core` as a dependency is a huge mystery to me.

**Comment by kerams** [comment]
b01fdba fixes this for me (indeed by updating the compiler service). Unless you still have any issues (apart from LinqPad), I'll release a new nuget package.
